---
title: "データ解析入門 レポート1"
author: "1841024 遠藤颯人"
output: html_document
---

**課題：carsのデータをK最近傍法で予測する際の，最良のKの値を調べために，次のようなコードを実行する．**


1. このコードを理解するのに必要なことをすべて説明する（1000字程度）．ヒント：K最近傍法とは何か，Kの値は何を意味するか，Kの値による予測性能の違いをどうやって比較するか
1. RStudioの「Knit」ボタンを押すとreport1.htmlができる．それをブラウザで開いて，問題がないことを確認する．
1. report1.Rmdをローカルにダウンロードし，名前を1234567-1.Rmdに変更（1234567の部分は自分の学生番号で置き換える），指定されたフォームで提出する．

```{r, results=FALSE, warning=FALSE, message=FALSE}
library(tidyverse) # コメント不要
library(caret)     # コメント不要
```

```{r}
set.seed(0) #毎回同じ乱数を発生させる
my_data <- cars #訓練に使うデータにcarsという名前を付ける

my_result <- train(form = dist ~ speed, #train関数で出力変数はdistance、入力変数はspeed
                   data = my_data, #dataはmy_dataを使用
                   method = "knn", #手法はk最近傍法
                   tuneGrid = expand.grid(k = c(1:15)),  #パラメータチューニングの範囲を細かく指定(kは長さ１から１５のベクトル)
                   trControl = trainControl(method = "repeatedcv", #train関数で反復的ｋ分割交差検証を使用
                                            number = 5, #５分割する
                                          repeats = 10)) #１０回繰り返す

my_result$results #my_resultsの結果
```

```{r}
plot(my_result) #my_resultをグラフ化
```

```{r}
my_result$results %>% filter(RMSE == min(my_result$results$RMSE)) #最小の値
```
